In [2]:
import numpy as np

In [11]:
array = np.zeros((8,8))
arraytranspose = np.zeros((8,8))

In [12]:
c = 1
for i in range(len(array)):
    for j in range(len(array)):
        array[i,j]=c
        arraytranspose[j, i]=c
        c+=1    

In [13]:
arraytranspose

array([[ 1.,  9., 17., 25., 33., 41., 49., 57.],
       [ 2., 10., 18., 26., 34., 42., 50., 58.],
       [ 3., 11., 19., 27., 35., 43., 51., 59.],
       [ 4., 12., 20., 28., 36., 44., 52., 60.],
       [ 5., 13., 21., 29., 37., 45., 53., 61.],
       [ 6., 14., 22., 30., 38., 46., 54., 62.],
       [ 7., 15., 23., 31., 39., 47., 55., 63.],
       [ 8., 16., 24., 32., 40., 48., 56., 64.]])

In [14]:
array

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12., 13., 14., 15., 16.],
       [17., 18., 19., 20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29., 30., 31., 32.],
       [33., 34., 35., 36., 37., 38., 39., 40.],
       [41., 42., 43., 44., 45., 46., 47., 48.],
       [49., 50., 51., 52., 53., 54., 55., 56.],
       [57., 58., 59., 60., 61., 62., 63., 64.]])

In [15]:
arraytranspose[((arraytranspose-3)%10==0) + (arraytranspose<40)* (arraytranspose>29)]=-99

In [16]:
arraytranspose

array([[  1.,   9.,  17.,  25., -99.,  41.,  49.,  57.],
       [  2.,  10.,  18.,  26., -99.,  42.,  50.,  58.],
       [-99.,  11.,  19.,  27., -99., -99.,  51.,  59.],
       [  4.,  12.,  20.,  28., -99.,  44.,  52.,  60.],
       [  5., -99.,  21.,  29., -99.,  45., -99.,  61.],
       [  6.,  14.,  22., -99., -99.,  46.,  54.,  62.],
       [  7.,  15., -99., -99., -99.,  47.,  55., -99.],
       [  8.,  16.,  24., -99.,  40.,  48.,  56.,  64.]])

ValueError: operands could not be broadcast together with shapes (35,) (39,) 

In [57]:
(array<40)* (array>29)

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [10]:
array3 = np.arange(0.4, 0.80, 0.01).reshape((8,5))

In [30]:
arraytot = np.append([np.transpose(array3)], [arraytranspose.transpose()]).transpose().reshape((8,13))

array([[  0.4 ,   0.45,   0.5 ,   0.55,   0.6 ,   0.65,   0.7 ,   0.75,
          0.41,   0.46,   0.51,   0.56,   0.61],
       [  0.66,   0.71,   0.76,   0.42,   0.47,   0.52,   0.57,   0.62,
          0.67,   0.72,   0.77,   0.43,   0.48],
       [  0.53,   0.58,   0.63,   0.68,   0.73,   0.78,   0.44,   0.49,
          0.54,   0.59,   0.64,   0.69,   0.74],
       [  0.79,   1.  ,   2.  , -99.  ,   4.  ,   5.  ,   6.  ,   7.  ,
          8.  ,   9.  ,  10.  ,  11.  ,  12.  ],
       [-99.  ,  14.  ,  15.  ,  16.  ,  17.  ,  18.  ,  19.  ,  20.  ,
         21.  ,  22.  , -99.  ,  24.  ,  25.  ],
       [ 26.  ,  27.  ,  28.  ,  29.  , -99.  , -99.  , -99.  , -99.  ,
        -99.  , -99.  , -99.  , -99.  , -99.  ],
       [-99.  ,  40.  ,  41.  ,  42.  , -99.  ,  44.  ,  45.  ,  46.  ,
         47.  ,  48.  ,  49.  ,  50.  ,  51.  ],
       [ 52.  , -99.  ,  54.  ,  55.  ,  56.  ,  57.  ,  58.  ,  59.  ,
         60.  ,  61.  ,  62.  , -99.  ,  64.  ]])

In [51]:
arrayaverage = []
arraymax = []
for i in arraytot.transpose():
    arrayaverage.append(i.sum()/len(i))
    arraymax.append(i.max())

data=np.append(np.append([arraytot],[arrayaverage]),[arraymax]).reshape((10,13))


In [52]:
np.savetxt('file.tsv', data, delimiter='\t', fmt='%.3f')