### Excercise 1, 2


In [1]:
import numpy as np

In [2]:
array = np.arange(1,65).reshape((8,8))
print(array)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]


In [3]:
arraytranspose = array.transpose()
print(arraytranspose)

[[ 1  9 17 25 33 41 49 57]
 [ 2 10 18 26 34 42 50 58]
 [ 3 11 19 27 35 43 51 59]
 [ 4 12 20 28 36 44 52 60]
 [ 5 13 21 29 37 45 53 61]
 [ 6 14 22 30 38 46 54 62]
 [ 7 15 23 31 39 47 55 63]
 [ 8 16 24 32 40 48 56 64]]


In [4]:
arraytranspose[( (arraytranspose-3)%10 == 0 ) + (arraytranspose < 40) * (arraytranspose > 29)] = -99
print(arraytranspose)

[[  1   9  17  25 -99  41  49  57]
 [  2  10  18  26 -99  42  50  58]
 [-99  11  19  27 -99 -99  51  59]
 [  4  12  20  28 -99  44  52  60]
 [  5 -99  21  29 -99  45 -99  61]
 [  6  14  22 -99 -99  46  54  62]
 [  7  15 -99 -99 -99  47  55 -99]
 [  8  16  24 -99  40  48  56  64]]


### Exercise 3

In [5]:
array3 = np.arange(0.4, 0.80, 0.01).reshape((8,5))
print(array3)

[[0.4  0.41 0.42 0.43 0.44]
 [0.45 0.46 0.47 0.48 0.49]
 [0.5  0.51 0.52 0.53 0.54]
 [0.55 0.56 0.57 0.58 0.59]
 [0.6  0.61 0.62 0.63 0.64]
 [0.65 0.66 0.67 0.68 0.69]
 [0.7  0.71 0.72 0.73 0.74]
 [0.75 0.76 0.77 0.78 0.79]]


In [9]:
arraytot = np.append(arraytranspose, array3, axis = 1)
print(arraytot)

[[  1.     9.    17.    25.   -99.    41.    49.    57.     0.4    0.41
    0.42   0.43   0.44]
 [  2.    10.    18.    26.   -99.    42.    50.    58.     0.45   0.46
    0.47   0.48   0.49]
 [-99.    11.    19.    27.   -99.   -99.    51.    59.     0.5    0.51
    0.52   0.53   0.54]
 [  4.    12.    20.    28.   -99.    44.    52.    60.     0.55   0.56
    0.57   0.58   0.59]
 [  5.   -99.    21.    29.   -99.    45.   -99.    61.     0.6    0.61
    0.62   0.63   0.64]
 [  6.    14.    22.   -99.   -99.    46.    54.    62.     0.65   0.66
    0.67   0.68   0.69]
 [  7.    15.   -99.   -99.   -99.    47.    55.   -99.     0.7    0.71
    0.72   0.73   0.74]
 [  8.    16.    24.   -99.    40.    48.    56.    64.     0.75   0.76
    0.77   0.78   0.79]]


In [48]:
arrayaverage = []
for i in arraytot.transpose():
    arrayaverage.append(i.sum()/len(i))
print(arrayaverage)

[-8.25, -1.5, 5.25, -20.25, -81.625, 26.75, 33.5, 40.25, 0.5750000000000002, 0.5850000000000002, 0.5950000000000002, 0.6050000000000002, 0.6150000000000002]


In [46]:
data = np.concatenate([arraytot, [arrayaverage]],axis = 0)
print(data)

[[  1.      9.     17.     25.    -99.     41.     49.     57.      0.4
    0.41    0.42    0.43    0.44 ]
 [  2.     10.     18.     26.    -99.     42.     50.     58.      0.45
    0.46    0.47    0.48    0.49 ]
 [-99.     11.     19.     27.    -99.    -99.     51.     59.      0.5
    0.51    0.52    0.53    0.54 ]
 [  4.     12.     20.     28.    -99.     44.     52.     60.      0.55
    0.56    0.57    0.58    0.59 ]
 [  5.    -99.     21.     29.    -99.     45.    -99.     61.      0.6
    0.61    0.62    0.63    0.64 ]
 [  6.     14.     22.    -99.    -99.     46.     54.     62.      0.65
    0.66    0.67    0.68    0.69 ]
 [  7.     15.    -99.    -99.    -99.     47.     55.    -99.      0.7
    0.71    0.72    0.73    0.74 ]
 [  8.     16.     24.    -99.     40.     48.     56.     64.      0.75
    0.76    0.77    0.78    0.79 ]
 [ -8.25   -1.5     5.25  -20.25  -81.625  26.75   33.5    40.25    0.575
    0.585   0.595   0.605   0.615]]


In [49]:
arraymax = []
for i in data:
    arraymax.append(i.max())
print(arraymax)

[57.0, 58.0, 59.0, 60.0, 61.0, 62.0, 55.0, 64.0, 40.25]


In [50]:
data2 = np.append(data, np.array([arraymax]).transpose(), axis = 1)
print(data2)

[[  1.      9.     17.     25.    -99.     41.     49.     57.      0.4
    0.41    0.42    0.43    0.44   57.   ]
 [  2.     10.     18.     26.    -99.     42.     50.     58.      0.45
    0.46    0.47    0.48    0.49   58.   ]
 [-99.     11.     19.     27.    -99.    -99.     51.     59.      0.5
    0.51    0.52    0.53    0.54   59.   ]
 [  4.     12.     20.     28.    -99.     44.     52.     60.      0.55
    0.56    0.57    0.58    0.59   60.   ]
 [  5.    -99.     21.     29.    -99.     45.    -99.     61.      0.6
    0.61    0.62    0.63    0.64   61.   ]
 [  6.     14.     22.    -99.    -99.     46.     54.     62.      0.65
    0.66    0.67    0.68    0.69   62.   ]
 [  7.     15.    -99.    -99.    -99.     47.     55.    -99.      0.7
    0.71    0.72    0.73    0.74   55.   ]
 [  8.     16.     24.    -99.     40.     48.     56.     64.      0.75
    0.76    0.77    0.78    0.79   64.   ]
 [ -8.25   -1.5     5.25  -20.25  -81.625  26.75   33.5    40.25    0.575
  

In [51]:
np.savetxt('exercise3.tsv', data2, delimiter='\t', fmt='%.3f')