# Numpy Library

Here I learn how to use numpy library

In [1]:
import numpy as np

### Generate numbers

In [3]:
np.arange(3,200,1.5) #(start, end, step)

array([  3. ,   4.5,   6. ,   7.5,   9. ,  10.5,  12. ,  13.5,  15. ,
        16.5,  18. ,  19.5,  21. ,  22.5,  24. ,  25.5,  27. ,  28.5,
        30. ,  31.5,  33. ,  34.5,  36. ,  37.5,  39. ,  40.5,  42. ,
        43.5,  45. ,  46.5,  48. ,  49.5,  51. ,  52.5,  54. ,  55.5,
        57. ,  58.5,  60. ,  61.5,  63. ,  64.5,  66. ,  67.5,  69. ,
        70.5,  72. ,  73.5,  75. ,  76.5,  78. ,  79.5,  81. ,  82.5,
        84. ,  85.5,  87. ,  88.5,  90. ,  91.5,  93. ,  94.5,  96. ,
        97.5,  99. , 100.5, 102. , 103.5, 105. , 106.5, 108. , 109.5,
       111. , 112.5, 114. , 115.5, 117. , 118.5, 120. , 121.5, 123. ,
       124.5, 126. , 127.5, 129. , 130.5, 132. , 133.5, 135. , 136.5,
       138. , 139.5, 141. , 142.5, 144. , 145.5, 147. , 148.5, 150. ,
       151.5, 153. , 154.5, 156. , 157.5, 159. , 160.5, 162. , 163.5,
       165. , 166.5, 168. , 169.5, 171. , 172.5, 174. , 175.5, 177. ,
       178.5, 180. , 181.5, 183. , 184.5, 186. , 187.5, 189. , 190.5,
       192. , 193.5,

### Generate numbers in a interval

In [7]:
np.linspace(0,100,100)

array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
         4.04040404,   5.05050505,   6.06060606,   7.07070707,
         8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
        12.12121212,  13.13131313,  14.14141414,  15.15151515,
        16.16161616,  17.17171717,  18.18181818,  19.19191919,
        20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
        24.24242424,  25.25252525,  26.26262626,  27.27272727,
        28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
        32.32323232,  33.33333333,  34.34343434,  35.35353535,
        36.36363636,  37.37373737,  38.38383838,  39.39393939,
        40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
        44.44444444,  45.45454545,  46.46464646,  47.47474747,
        48.48484848,  49.49494949,  50.50505051,  51.51515152,
        52.52525253,  53.53535354,  54.54545455,  55.55555556,
        56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
        60.60606061,  61.61616162,  62.62626263,  63.63

### Generate random numbers

In [9]:
np.random.rand(5)

array([0.08442131, 0.83774979, 0.96289465, 0.41570804, 0.62303393])

Generate distribution normal numbers

In [10]:
np.random.randn(5)

array([-2.16526832, -1.03236673, -0.17181051, -0.89047082, -0.36501966])

Modify arrays

COncatenate numpy arrays

In [13]:
np.concatenate(([1,2,3],[4,5,6],[7,8,9]))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Insert a element in end of numpy array

In [15]:
x = np.array([[1,2,3,4],[5,6,7,8]])

In [18]:
?np.insert

### Array Operations

### Array